name: Bornium Sistemas 11.0
#run-name: Rodando
on: 
  push:
    branches:
    - main
    paths:
      - 'ControleVersao.txt'  # Somente vai ser executada quando este arquivo for alterado
jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Substitua pela sua região
      

