name: Bornium Sistemas 11.0
#run-name: Rodando
on: 
  push:
    paths:
      - 'ControleVersao.txt'  # Somente vai ser executada quando este arquivo for alterado
jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: teste
        run: echo "paulo cesar medeiros"