# This is a basic workflow to help you get started with Actions

name: Atualização Bornium 11.0

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

